### ISSUE TITLE
Crear el Html de la pagina

### ISSUE THREAD

**Issue by Zurita96** [GleziDamaris/paises-segundo-parcial#1]
Se tiene que crear el html para visualizar la pagina

**Comment by GleziDamaris** [comment]
Después de realiza el issue 5 procedimos a realizar el número 1, creando un archivo llamado index.html dentro de la carpeta principal que se nombró "countries", además incluimos en este archivo la estructura básica de html

**Comment by GleziDamaris** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Countries</title>
</head>
<body>
    
</body>
</html>`
