### ISSUE TITLE
Crear la carpeta donde se guardara el proyecto

### ISSUE THREAD

**Issue by Zurita96** [GleziDamaris/paises-segundo-parcial#5]
Crear una carpeta donde se guardara el proyecto, creando donde se guardara la hoja de estilos, el java scrip y el html

**Comment by GleziDamaris** [comment]
Para poder comenzar con los primeros issues debimos iniciar con el issue #5 ya que de aquí partimos para crear los archivos y carpetas que utilizaremos

**Comment by GleziDamaris** [comment]
![image](https://github.com/GleziDamaris/paises-segundo-parcial/assets/114638431/cfb62325-c0dc-4bd5-8639-2dcbed4df0ea)
