### ISSUE TITLE
Crear la lista de paises

### ISSUE THREAD

**Issue by Zurita96** [GleziDamaris/paises-segundo-parcial#6]
Crear la lista con los paises que se encuentren en la siguiente API: https://restcountries.com/v3.1/all

**Comment by Ramiro440** [comment]
Se atraso la tarea, ya que tuve inconvenientes con la api al usarlaen  js, ya hice las debidas preguntas  al profesor, esperando su respuesta, a mas tardar el viernes estara

**Comment by GleziDamaris** [comment]
Confirmo de recibida la información, previamente se había notificado el retraso de esta tarea, en espera de los comentarios del profesor

**Comment by 8devmx** [comment]
Fecha de entrega: 24 de Junio
