### ISSUE TITLE
Conectar las sub-paginas

### ISSUE THREAD

**Issue by Zurita96** [GleziDamaris/paises-segundo-parcial#8]
Conectar los html's de las paginas correspondientes a su API por ejemplo, del menú de paises a sus divisas, etc.

**Comment by GleziDamaris** [comment]
Hola @Zurita96 tengo una duda con respecto a esta tarea, te pido amablemente que por favor me especifiques un poco más el resultado final que se desea obtener. 
Lo que supongo es de mi pagina principal, la cual es paises, al momento en que le de click a una opcion de mi barra de menu me mande al html interno de esa opción.
Es decir, que de mi menu en mi pagina principal de click  a la opción de "Divisas" y me mande a la pagina de divisas de todos los paises. 
Quedo atenta a comentarios, saludos

**Comment by GleziDamaris** [comment]
- [ x] Se crea html de currency enlanzando los ditstintos archivos html

![image](https://github.com/GleziDamaris/paises-segundo-parcial/assets/114638431/a3833b79-13a3-4edf-8a18-afd9b5d4b688)

- [x] Se crea html de language enlanzando los ditstintos archivos html

![image](https://github.com/GleziDamaris/paises-segundo-parcial/assets/114638431/e5dacca4-d036-4d75-898c-66d759f1c57d)

- [x] Se crea html de capital enlanzando los ditstintos archivos html

![image](https://github.com/GleziDamaris/paises-segundo-parcial/assets/114638431/b7e15b6e-b622-478f-bae2-971622f16e88)
